#!/bin/bash

# Crypto Assets Monitor - Project Tree
# This script shows the complete project structure

echo "=================================="
echo "  CRYPTO ASSETS MONITOR PROJECT"
echo "=================================="
echo ""
echo "crypto-assets-monitor/"
echo "│"
echo "├── 📦 packages/"
echo "│   └── types/                        # Shared TypeScript types"
echo "│       ├── src/"
echo "│       │   └── index.ts              # 150+ lines of type definitions"
echo "│       ├── package.json"
echo "│       └── tsconfig.json"
echo "│"
echo "├── 🔧 services/"
echo "│   ├── ingestion-service/            # Fetch prices from CoinGecko"
echo "│   │   ├── src/"
echo "│   │   │   ├── index.ts              # Main entry point"
echo "│   │   │   ├── coingecko.client.ts   # API client"
echo "│   │   │   ├── redis.client.ts       # Redis publisher"
echo "│   │   │   ├── ingestion.service.ts  # Business logic"
echo "│   │   │   ├── config.ts             # Configuration"
echo "│   │   │   └── logger.ts             # Logging setup"
echo "│   │   ├── .env.example"
echo "│   │   ├── Dockerfile"
echo "│   │   ├── package.json"
echo "│   │   └── tsconfig.json"
echo "│   │"
echo "│   ├── analysis-service/             # Check alerts & store data"
echo "│   │   ├── src/"
echo "│   │   │   ├── index.ts              # Main entry point"
echo "│   │   │   ├── database.client.ts    # TimescaleDB client"
echo "│   │   │   ├── redis.client.ts       # Redis subscriber"
echo "│   │   │   ├── analysis.service.ts   # Alert checking logic"
echo "│   │   │   ├── api.server.ts         # REST API endpoints"
echo "│   │   │   ├── config.ts             # Configuration"
echo "│   │   │   └── logger.ts             # Logging setup"
echo "│   │   ├── .env.example"
echo "│   │   ├── Dockerfile"
echo "│   │   ├── package.json"
echo "│   │   └── tsconfig.json"
echo "│   │"
echo "│   ├── notification-service/         # Send email notifications"
echo "│   │   ├── src/"
echo "│   │   │   ├── index.ts              # Main entry point"
echo "│   │   │   ├── email.provider.ts     # Email sending (SMTP)"
echo "│   │   │   ├── redis.client.ts       # Redis subscriber"
echo "│   │   │   ├── notification.service.ts # Notification logic"
echo "│   │   │   ├── config.ts             # Configuration"
echo "│   │   │   └── logger.ts             # Logging setup"
echo "│   │   ├── .env.example"
echo "│   │   ├── Dockerfile"
echo "│   │   ├── package.json"
echo "│   │   └── tsconfig.json"
echo "│   │"
echo "│   └── gateway-service/              # WebSocket + API Gateway"
echo "│       ├── src/"
echo "│       │   ├── index.ts              # Main entry point"
echo "│       │   ├── websocket.manager.ts  # WebSocket logic"
echo "│       │   ├── redis.client.ts       # Redis subscriber"
echo "│       │   ├── config.ts             # Configuration"
echo "│       │   └── logger.ts             # Logging setup"
echo "│       ├── .env.example"
echo "│       ├── Dockerfile"
echo "│       ├── package.json"
echo "│       └── tsconfig.json"
echo "│"
echo "├── 🎨 frontend/                      # React application"
echo "│   ├── src/"
echo "│   │   ├── components/"
echo "│   │   │   ├── PriceCard.tsx         # Price display card"
echo "│   │   │   ├── AlertList.tsx         # User alerts list"
echo "│   │   │   ├── CreateAlertModal.tsx  # Alert creation form"
echo "│   │   │   └── AlertNotification.tsx # Popup notification"
echo "│   │   ├── store/"
echo "│   │   │   ├── websocket.store.ts    # WebSocket state"
echo "│   │   │   └── alert.store.ts        # Alert state"
echo "│   │   ├── App.tsx                   # Main app component"
echo "│   │   ├── main.tsx                  # React entry point"
echo "│   │   └── index.css                 # Tailwind styles"
echo "│   ├── index.html"
echo "│   ├── vite.config.ts"
echo "│   ├── tailwind.config.js"
echo "│   ├── postcss.config.js"
echo "│   ├── package.json"
echo "│   ├── tsconfig.json"
echo "│   └── tsconfig.node.json"
echo "│"
echo "├── 🐳 Docker/"
echo "│   ├── docker-compose.yml            # Multi-service orchestration"
echo "│   ├── services/*/Dockerfile         # Individual service images"
echo "│   └── .env                          # Environment variables"
echo "│"
echo "├── 📚 Documentation/"
echo "│   ├── README.md                     # Main documentation (400+ lines)"
echo "│   ├── QUICKSTART.md                 # 5-minute setup guide"
echo "│   ├── API.md                        # Complete API docs (500+ lines)"
echo "│   ├── ARCHITECTURE.md               # Design decisions (450+ lines)"
echo "│   └── SUMMARY.md                    # Project summary"
echo "│"
echo "├── 🔧 Configuration/"
echo "│   ├── package.json                  # Root package (workspaces)"
echo "│   ├── turbo.json                    # Turborepo config"
echo "│   ├── tsconfig.base.json            # Base TypeScript config"
echo "│   ├── Makefile                      # Convenient commands"
echo "│   └── .gitignore                    # Git ignore rules"
echo "│"
echo "└── 🗄️ Infrastructure/ (via Docker Compose)"
echo "    ├── Redis (Port 6379)             # Message broker"
echo "    └── TimescaleDB (Port 5432)       # Time-series database"
echo ""
echo "=================================="
echo "  KEY STATISTICS"
echo "=================================="
echo ""
echo "📊 Total Files:        60+"
echo "💻 Lines of Code:      3,500+"
echo "🔧 Backend Services:   4"
echo "🎨 Frontend:           1 React app"
echo "📦 NPM Packages:       30+"
echo "🗄️ Database Tables:    2"
echo "🌐 API Endpoints:      5 REST + WebSocket"
echo "📄 Documentation:      5 comprehensive guides"
echo ""
echo "=================================="
echo "  TECHNOLOGY STACK"
echo "=================================="
echo ""
echo "Backend:"
echo "  • Node.js 18+"
echo "  • TypeScript 5.3+"
echo "  • Express.js"
echo "  • ws (WebSocket)"
echo "  • Pino (logging)"
echo ""
echo "Frontend:"
echo "  • React 18"
echo "  • TypeScript"
echo "  • Vite"
echo "  • Tailwind CSS"
echo "  • Zustand"
echo ""
echo "Infrastructure:"
echo "  • Redis (Pub/Sub)"
echo "  • TimescaleDB"
echo "  • Docker"
echo "  • Turborepo"
echo ""
echo "=================================="
echo "  QUICK COMMANDS"
echo "=================================="
echo ""
echo "Setup:     make quickstart"
echo "Run:       make dev"
echo "Docker:    make docker-up"
echo "Database:  make db-connect"
echo "Help:      make help"
echo ""
echo "=================================="
